### PR TITLE
CTL-824

### PR DESCRIPTION
**Pull request by michu**
ModelBase.editableobject should check for duplicated BeginEdit(), EndEdit(), CancelEdit()

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Do you use ReSharper? If so, please hit CTRL K + D so the spaces are correctly aligned next time.

**Comment by michu** [comment]
No I don't use Reshaper, no licence. If you can tell me where spaces are not correctly aligned then I will check next time before making PR.

**Comment by GeertvanHorrik** [comment]
Space between if and the ()

**Comment by GeertvanHorrik** [comment]
Thanks a lot, looks good! Did you receive my email? If so, please respond via email.

**Pull request merged**
