### PR TITLE
(+) #1168 Add ParallelHelper.ExecuteInParallelAsync

### LINKED ISSUE #1168: Add ParallelHelper.ExecuteInParallelAsync
This should take a list of Func<Task<T>> where it should run in pre-defined batches.

### PR DESCRIPTION
**Pull request by alexfdezsauco**
Fixes #1168

### Changes proposed in this pull request:

- Add ParallelHelper.ExecuteInParallelAsync

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Looks great. Can you add a unit test like we did for the non-async one?

**Comment by alexfdezsauco** [comment]
Are you sure about the existence of non-async method tests?

**Comment by GeertvanHorrik** [comment]
In my head I wrote them, let me look for them.

**Comment by GeertvanHorrik** [comment]
I was wrong, adding it like this.

**Pull request merged**
