### PR TITLE
Master

### PR DESCRIPTION
**Pull request by gmlohaels**
Hey.. How about  MVVM automatic mapping improvements

First one
```c#

------------------------------------------
  public T XGetValue<T>([CallerMemberNameAttribute] string name="")
        {
            return GetValue<T>(name); //now i use Catel's GetValue
        }
------------------------------------------
        public void XSetValue(object value, [CallerMemberNameAttribute] string name = "")
        {
            SetValue(name,value);  //now i use Catel's SetValue
        }

------------------------------------------
//This is EXAMPLE Property now....
        [ViewModelToModel(nameof(Model))]
        public bool AllowSelected
        {
            get{return XGetValue<bool>();}
            set { XSetValue(value); }
        }
```
------------------------------------------
This can be OVERLOADed methods to existing GetValue/SetValue.
[CallerMemberNameAttribute]  set name of property automatically.

Next thing is add some method to ViewModelBase

That register all properties (RegisterProperty) automatically for ALL properties that has a   [ViewModelToModel(nameof(Model))]

I really dont understand why it must be going manually.

Little  Example (just as pseudocode)

```c#
public void RegisterAllPropertiesThatHasViewModelAttribute()
{
  this.GetType().GetAttributes.Where(t=t.HasAttribute(typeof(ViewModelToModel)).ForEach(t=>t.RegisterProperty).......
}
```
And this ... is gone automatically.

```c#
public static readonly PropertyData PersonProperty = RegisterProperty("Person", typeof(IPerson));
 public static readonly PropertyData SettingsDataProperty =   RegisterProperty("SettingsData", typeof(SettingsDataObject));
```

and 100 millions of them.....

The next thing is.. Why we must specify 
```c#
[ViewModelToModel(nameof(Model))]
```

Name of Model ? I  guess many ViewModels has only one Model
so maybe Overload which Gets FirstOrDefault (and throws if few [Model] in VM class found)

Also.
Catel.Localization in Catel Examples is broken. 

I Can write working code if u interested on it as pull request.

Thank you.

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Did you read about Catel.Fody? It does most that you are describing.

1. Using automated properties getters / setters:

```
[Model]
public MyModel Model { get; private set; }

[ViewModelToModel("Model")]
public bool AllowSelected { get; set; }
```

2. The reason you must specify the model is because you can have multiple models

3. You can automate (expose) properties like this:

```
[Model]
[Expose("MyProperty1")]
[Expose("MyProperty2")]
public MyModel Model { get; private set; }
```

Then the properties will be defined on the view model (but not accessible in code because they are weaved in afterwards).

4. I will update the examples soonish, but since resources are limited, we don't have time for everything (it's still free and open-source, not a commercial thing).

**Comment by gmlohaels** [comment]
Catel.Fody is broken like Catel.Localization.Examples. No way to bind Model to VM.. its just doesnt work correctly.

and i dont really understand why Base framework cant include things like described above.

Your reply is all based on Catel.Fody. I'm talking about Catel Core package. its totally different.

**Comment by GeertvanHorrik** [comment]
Then I am not sure what you mean. Can you try to explain in a different way what you are trying to achieve or what you are expecting?

**Comment by gmlohaels** [comment]
One more thing about 
```
2) The reason you must specify the model is because you can have multiple models
```

So in .NET LINQ we have First + FirstOrDefault + Single  methods for it.

Yes i can have multiply models but also i can have only one. So i  offer some thing's for ONE model

**Comment by gmlohaels** [comment]
Lets forget about broken catel.fody in one minute. 
We have official documentation that offers us to do a many steps to achieve some result.

I am talking about Core features , and  there is a way to simplify basic operations and reduce the code using way am talking about.

**Comment by GeertvanHorrik** [comment]
If you want to go into a chat, I think gitter is a better platform. gitter.im/catel

**Comment by GeertvanHorrik** [comment]
I think we discussed all of this on JIRA. See 

* https://catelproject.atlassian.net/browse/CTL-757
* https://catelproject.atlassian.net/browse/CTL-758
* https://catelproject.atlassian.net/browse/CTL-759

**Pull request closed without merging**
