### PR TITLE
hot fixes to 5.12.0

### LINKED ISSUE #1506: ObservableDictionary NotifyCollectionChanged Event Storm
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] UWP
 - [x] iOS
 - [x] Android
 - [x] .NET Standard
 - [x] .NET Core

## Component

`ObservableDictionary`

## Version of Library

5.12.0

## Version of OS(s) listed above with issue

Windows 10 Enterprise

## Steps to Reproduce
1. Instantiate a new instance of `ObservableDictionary` with several hundreds (or thousands) of objects

## Expected Behavior

Instantiation should suppress all notifications until the collection has been populated.

## Actual Behavior

UI becomes inundated with NotifyCollectionChanged events.

## Discussion

While this is an edge case, I still dropped the ball on this one. I did not take care to ensure that an event storm would not occur upon the instantiation of this with a huge collection. We actually discovered it today attempting to populate an ObservableDictionary with about 16,000 items and the whole program just ground to a halt.

Essentially what needs to be done is the implementation of `SuspendChangeNotifications` similar to what of `FastObservableCollection` does both in it's constructor and as an outside disposable method. I can have a PR with the fixes for this but it probably won't be for a few days given the holidays.

### LINKED ISSUE #1509: Make Generic Catel.Collections.SuspensionContext Public
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
This actually came up as a result of #1506 and #1508. It would be nice of `SuspensionContext<T>` was actually made `public`. Right now it is `internal` and only the non-generic `SuspensionContext` is `public`. 

## API Changes
Change `Catel.Collections.SuspensionContext` from `internal` to `public`

## Intended Use Case

We actually have several use cases where we use `SuspensionContext<T>` in our end implementation and to avoid overlap we maintain our own fork of Catel to expose it rather than override it at the namespace level.

### LINKED ISSUE #1510: Fix a potential NullReferenceException in FastMemberInvoker
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] UWP
 - [x] iOS
 - [x] Android
 - [x] .NET Standard
 - [x] .NET Core

## Component

Catel.Core

## Version of Library
6.0
## Steps to Reproduce
this line holds a potential `NullRefrenceException` when `getterExpression` is null (that i encountered randomly during unit tests)

https://github.com/Catel/Catel/blob/398b6c822e5450e2f7bb001104dc1771496fcfe5/src/Catel.Core/Reflection/FastMemberInvoker/FastMemberInvoker.caches.g.tt#L54

it should be moved exactly below this line 
https://github.com/Catel/Catel/blob/398b6c822e5450e2f7bb001104dc1771496fcfe5/src/Catel.Core/Reflection/FastMemberInvoker/FastMemberInvoker.caches.g.tt#L51

same problem applies to all the methods below it.

## Actual Behavior

### LINKED ISSUE #1511: ObservableDictionary Performance Issue with Large Collections
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] UWP
 - [x] iOS
 - [x] Android
 - [x] .NET Standard
 - [x] .NET Core

## Component

`Catel.MVVM.Collections.ObservableDictionary`

## Version of Library

5.12.0

## Version of OS(s) listed above with issue

Windows 10 Enterprise

## Steps to Reproduce
1. Instantiate an `ObservableDictionary` with a large collection (10,000 or more items)

## Expected Behavior

Process consumption time should be negligible.

## Actual Behavior

Process can take up to several 10s of seconds to run through the collection.

## Discussion

This is a separate bug but related to #1506 indirectly as it was discovered. I'm not sure if I would consider this an edge case, maybe it is, maybe it isn't. I know for us it isn't because we have some business processes that use drop-downs with this many objects (note: use of VirtualizingStackPanel is strongly recommended for that). 

The problem isn't with the implementation of the `IndexedKeyedCollection` as that is fast. The issue is actually with the `Insert` method. In order to handle the events properly an index has to be calculated and the use of `Collection.IndexOf()`. The problem is this is taking a huge amount of time:

image

I'm not exactly sure how to approach this issue yet but it's an obvious bottleneck. Also whether or not it's critical to 5.12.x is up to interpretation given the use cases.

### PR DESCRIPTION
**Pull request by bigworld12**
### Description of Change ###

some hot fixes

### Issues Resolved ### 

- fixes #1510
- fixes #1511 
- fixes #1509 
- fixes #1506 

### API Changes ###

 
None

### Platforms Affected ### 

- All
- WPF
- UWP
- iOS
- Android

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by bigworld12** [comment]
sorry for the typo in commit message, it's `FastObservableDictionary` not `Collection`

**Comment by GeertvanHorrik** [comment]
Just created a hotfix branch. Do you mind if I manually merge these changes?

**Comment by bigworld12** [comment]
that's perfectly fine

**Comment by GeertvanHorrik** [comment]
Most of this has been manually merged into the hotfix branch exception for the observable dictionary. Is this one ready to be merged as well to fix the event storm?

**Comment by bigworld12** [comment]
I haven't implemented the suspension logic in all the methods yet, if you can do it, that would be great!

**Comment by GeertvanHorrik** [comment]
I am not sure whether we should fix this for 5.12 or just do a better rewrite for 6.0. What are your thoughts @vaecors ?

**Comment by bigworld12** [comment]
how about we make the old ObservableDictionary call the new FastObservableDicyionary
while leaving its public api as it is

**Comment by GeertvanHorrik** [comment]
That could be a great idea. The question is whether the FastObservableDictionary is ready or does it need more work? In that case we might delay the hotfix until it's ready (unless it;s gonna take weeks, then we might release 2 hotfixes).

**Comment by bigworld12** [comment]
I am currently implementing the suspension logic in the remaining methods, it could take a couple of minutes

**Comment by vaecors** [comment]
> 
> 
> how about we make the old ObservableDictionary call the new FastObservableDicyionary
> while leaving its public api as it is

I have absolutely no issue with this, it avoids the breaking change but takes advantage of the re-write. Then towards a 6.0 milestone the old class can be marked as obsolete just so dead code gets eventually removed.

**Comment by bigworld12** [comment]
@vaecors  @GeertvanHorrik I pushed a new commit with the suspension logic, do you mind testing it for performance/bugs

**Comment by bigworld12** [comment]
Incidently, i think using the Insert/RemoveMultipleValues method is faster without using `SuspendChangeNotifications`, since it already groups the changed items together

**Comment by bigworld12** [comment]
@GeertvanHorrik i've rebased the branch onto your changes so they are ready to merge

**Comment by bigworld12** [comment]
I am replacing this PR with #1513

**Comment by GeertvanHorrik** [comment]
Thanks!

**Pull request closed without merging**
