### PR TITLE
CTL-887 Fix for GetString resolving wrong resources for non-neutral cultures in metro apps

### PR DESCRIPTION
**Pull request by afussit**

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Looks good. Are you using UWP (WinRT 2.0) or WinRT 1.0?

**Comment by afussit** [comment]
I tested it on both platforms (WIN81, UAP100).

Just a question: Is the ResourceLoader part (GetResourceManager) necessary in WPRT81? i my tests it was not needed....

**Comment by GeertvanHorrik** [comment]
Not sure, I haven't written a WPRT81 app in a while. To be honest we were thinking of only supporting WPF, UWP and Xamarin from 5.0. Why would you want to support WPRT?

**Comment by afussit** [comment]
Sorry for the misunderstanding, don't want to support WPRT.... I made tests in WIN81 and UAP100 without GetResourceManager and it worked (no test in WPRT) .... Shall i remove it?

**Comment by GeertvanHorrik** [comment]
Let's keep it as is for now. Thanks for the PR.

**Pull request merged**
