### PR TITLE
Could not load 'ModuleWeaver' from Catel.Fody

### PR DESCRIPTION
**Pull request by SkyQuant**
```
Severity	Code	Description	Project	File	Line
Error		Fody: Could not load 'ModuleWeaver' from 'Catel.Fody, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null' due to ReflectionTypeLoadException.
It is possible you need to update the package.
exception.LoaderExceptions:
System.IO.FileLoadException: Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'	
```

This message appearing after Fody 2.8 installation (with Controls 4.2). File *FodyWeavers.xml* in the root of WPF app. Earlier downgradin to 2.7 helped (with v4.1).

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Why do you create a PR for an issue? Please create an issue in the official issue tracker at:

http://www.catelproject.com/support/issue-tracker

**Comment by GeertvanHorrik** [comment]
But the solution is to update Fody and all extensions to the latest version.

**Comment by SkyQuant** [comment]
What the latest version? The problem with v4.2 + v2.8.

**Comment by GeertvanHorrik** [comment]
Latest fody version is 1.29.3

**Comment by SkyQuant** [comment]
I see 2.8.0 only as the latest
https://yadi.sk/i/ICYbqjFJisJf7

**Comment by GeertvanHorrik** [comment]
That's *Catel.Fody*, I am talking about *Fody*.

**Comment by SkyQuant** [comment]
Thanks. I should play with dependensies.
Next time I'll try to post to issue-tracker which didn't use before.

**Comment by SkyQuant** [comment]
Could you add "Issue" menu option (button) to ask a question?

**Comment by GeertvanHorrik** [comment]
We have an official issue tracker to ask questions / report bugs.

**Comment by SkyQuant** [comment]
I need unofficial forum for stupid question like how to embed *catel:UserControl* to Telerik Docking (http://docs.telerik.com/devtools/wpf/controls/raddocking/overview2).

**Comment by SkyQuant** [comment]
Just UserControl works well, but catel:UserControl + linked ViewModel call exaption

**Comment by SkyQuant** [comment]
official issue tracker needs registration

**Comment by GeertvanHorrik** [comment]
Correct, is it too much effort? You are asking for free help after all?

**Comment by SkyQuant** [comment]
Just short communication. Just rapidly get to know if it possible to insert Catel control to Telerik pad or they are not compatable.

**Comment by GeertvanHorrik** [comment]
Then use the chat feature on gitter.

**Comment by SkyQuant** [comment]
Sorry, what is gitter?

**Comment by SkyQuant** [comment]
Will you answer the question about Telerik if I ask on StockOverflow? I simply not sure whether it correct issue.

**Comment by GeertvanHorrik** [comment]
Just google Gitter or check the readme (it's on the top).

**Comment by SkyQuant** [comment]
Suppose one variant of solution is to link VM manually, deleting *:catel* in first tag
```
<UserControl x:Class="VisualStudioDocking.View.ManagerView"
                   xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                   xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                   xmlns:telerik="http://schemas.telerik.com/2008/xaml/presentation"
                   xmlns:vm="clr-namespace:VisualStudioDocking.ViewModel"
                   xmlns:catel="http://catel.codeplex.com">
<UserControl.DataContext>
    <vm:ManagerViewModel></vm:ManagerViewModel>
</UserControl.DataContext>
    <catel:StackGrid>
        <catel:StackGrid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
        </catel:StackGrid.RowDefinitions>
        
        <Label Content="{Binding Title}" />
        <Label Content="Here goes your real content" />
    </catel:StackGrid>
    
</UserControl>

**Comment by SkyQuant** [comment]
Anyway constructur without parametr requared. That's impossible:
```
        public ManagerViewModel(IUIVisualizerService uiVisualizerService)
        {
            _uiVisualizerService = uiVisualizerService;
        }

**Comment by GeertvanHorrik** [comment]
Please use a different mechanism to ask questions as I explained earlier.

**Pull request closed without merging**
