### PR TITLE
Move collections to Catel.Core

### LINKED ISSUE #1506: ObservableDictionary NotifyCollectionChanged Event Storm
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] UWP
 - [x] iOS
 - [x] Android
 - [x] .NET Standard
 - [x] .NET Core

## Component

`ObservableDictionary`

## Version of Library

5.12.0

## Version of OS(s) listed above with issue

Windows 10 Enterprise

## Steps to Reproduce
1. Instantiate a new instance of `ObservableDictionary` with several hundreds (or thousands) of objects

## Expected Behavior

Instantiation should suppress all notifications until the collection has been populated.

## Actual Behavior

UI becomes inundated with NotifyCollectionChanged events.

## Discussion

While this is an edge case, I still dropped the ball on this one. I did not take care to ensure that an event storm would not occur upon the instantiation of this with a huge collection. We actually discovered it today attempting to populate an ObservableDictionary with about 16,000 items and the whole program just ground to a halt.

Essentially what needs to be done is the implementation of `SuspendChangeNotifications` similar to what of `FastObservableCollection` does both in it's constructor and as an outside disposable method. I can have a PR with the fixes for this but it probably won't be for a few days given the holidays.

### LINKED ISSUE #1507: Move Catel.MVVM collections to Catel.Core collections
## Summary
currently we can't use ObservableDictionary or FastObservableCollection or any collection defined in Catel.MVVM in a .net standard project

## API Changes
move all the collections to Catel.Core project 

## Intended Use Case
using the collections outside of .net core applications

### LINKED ISSUE #1509: Make Generic Catel.Collections.SuspensionContext Public
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
This actually came up as a result of #1506 and #1508. It would be nice of `SuspensionContext<T>` was actually made `public`. Right now it is `internal` and only the non-generic `SuspensionContext` is `public`. 

## API Changes
Change `Catel.Collections.SuspensionContext` from `internal` to `public`

## Intended Use Case

We actually have several use cases where we use `SuspensionContext<T>` in our end implementation and to avoid overlap we maintain our own fork of Catel to expose it rather than override it at the namespace level.

### PR DESCRIPTION
**Pull request by bigworld12**
### Description of Change ###

1. moves `FastObservableCollection`, `FastBindingList` and `ObservableDictionary` to Catel.Core instead of Catel.MVVM
2. creates `DispatcherFastObservableCollection` ,`DispatcherFastBindingList`, `DispatcherObservableDictionary`
3. makes `ObservableDictionary` a fast `ObservableDictionary` by incorporating the suspension logic

### Issues Resolved ### 
- fixes #1507 
- fixes #1506 
- fixes #1509 
### API Changes ###

 
None

### Platforms Affected ### 

- All

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by bigworld12** [comment]
@GeertvanHorrik @vaecors I made some changes, but I am not sure if i got the suppression right, would you please check ?

**Comment by vaecors** [comment]
@bigworld12 I took a different approach and did not use the generic SuppressionContext but the non-generic one because honestly I don't see a use case where a value would be implementing ModelBase. The idea behind ObservableDictionary is an assisted lookup for ComboBox controls but hey anything is possible.

```csharp
private SuspensionContext _suspensionContext;

public IDisposable SuspendChangeNotifications()
{
    if ( _suspensionContext is null )
    {
        _suspensionContext = new SuspensionContext();
    }
    else if ( _suspensionContext != null )
    {
        throw Log.ErrorAndCreateException<InvalidOperationException>("There is already a suspension state active");
    }

    return new DisposableToken<ObservableDictionary<TKey, TValue>>(this,
        x => x.Instance._suspensionContext.Increment(),
        x =>
        {
            x.Instance._suspensionContext.Decrement();

            if ( x.Instance._suspensionContext.Counter != 0 )
            {
                return;
            }

            x.Instance.OnCollectionChanged();
            x.Instance._suspensionContext = null;
        },
        _suspensionContext);
}
```

Then in all the `OnCollectionChanged` methods I put this short circuit:

```csharp
if ( !(_suspensionContext is null) && _suspensionContext.Counter != 0 )
{
    return;
}
```

In the constructor and extension methods I put this:

```csharp
using ( SuspendChangeNotifications() )
{
    foreach ( KeyValuePair<TKey, TValue> pair in dictionary )
    {
        Add(pair.Key, pair.Value);
    }
}
```

**Comment by bigworld12** [comment]
@vaecors the generic method provides the exact list of changes, and prevents us from looping through the entire dictionary for each suppression

**Comment by vaecors** [comment]
@bigworld12 fair point, this was not a committed fix anyway. It was a quick fix on our end until we identified that there was a much larger issue with the 16,000 items not related to the event storm.

**Comment by bigworld12** [comment]
I still need to make extension methods and constructors for adding multiple items, and also rewrite the comments that were copied from `FastObservableCollection`

**Comment by bigworld12** [comment]
I am not sure why, but this test 
https://github.com/Catel/Catel/blob/95abb21dd1249b5ee5d429499895a165371d6f15/src/Catel.Tests/Collections/FastObservableCollectionFacts.cs#L102
fails when i use `DispatcherFastObservableCollection`,
but works well when i use `FastObservableCollection`, which makes no sense to me

**Comment by bigworld12** [comment]
going to separate this into 2 PRs

**Pull request closed without merging**
