### PR TITLE
ViewModelCommandManager dictionary KeyNotFoundException bugfix

### PR DESCRIPTION
**Pull request by abakaa**

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Did you really get an exception like this?

**Comment by GeertvanHorrik** [comment]
See the reference source. Setting a value represents an Insert:

http://referencesource.microsoft.com/#mscorlib/system/collections/generic/dictionary.cs,180

**Comment by abakaa** [comment]
capture

Here is part of my stacktrace which i received from a client.
The fact is that i get this exception rarely and not from the same viewmodel.
I create and enumerate dozens of viewmodels in the beginning of the application by the way.

What you say makes sense, but i couldn`t find out any other solution.

**Comment by GeertvanHorrik** [comment]
It's this line breaking the stuff:

```
return _instances[viewModel.UniqueIdentifier];
```

Are you doing vm initialization in different threads?

**Comment by GeertvanHorrik** [comment]
Not sure why that part isn't being locked btw. Will surround it with a lock.

**Comment by GeertvanHorrik** [comment]
Created this issue: https://catelproject.atlassian.net/browse/CTL-663

**Comment by abakaa** [comment]
Yes i do. I realize this now.
Is there a possible countermeasure that i can take ?

**Comment by abakaa** [comment]
Ah, okay. I will be following then.

**Comment by abakaa** [comment]
Thanks, do i need to pull another request ? Or you handle it ?

**Comment by GeertvanHorrik** [comment]
Closing this one, will be fixed using the issue.

**Comment by GeertvanHorrik** [comment]
It's fixed, releasing a new build now.

**Pull request closed without merging**
