### PR TITLE
#1252 Catel.MVVM.Xamarin.Forms MessageBox showing without buttons

### LINKED ISSUE #1252: Catel.MVVM.Xamarin.Forms MessageBox showing without buttons
Catel.MVVM.Xamarin.Forms (5.9 b7)
I try show message:
`messageService.ShowAsync("please press OK or Cancel", "Hello", MessageButton.OKCancel);`
Message is displayed, but without buttons.

Platform:
.NET Standard 2:

### Expected behaviour
Show message with requested buttons

### Actual behaviour
Buttons is not visible

test project:
[MessageTest.zip](https://github.com/Catel/Catel/files/2787571/MessageTest.zip)

### PR DESCRIPTION
**Pull request by GreenKn1ght**
Fixes #1252.

### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:
Before:
image
After:
image

### CODE REVIEW

**Comment by GreenKn1ght** [comment]
image

**Comment by GeertvanHorrik** [comment]
Thanks for updating the release history, very thoughtful! I hope you don't mind that we put this in 5.10 though ;-)

**Comment by GreenKn1ght** [comment]
Not mind at all. I'll update PR soon.

**Comment by GreenKn1ght** [comment]
Oh, there is no way to change source branch...

**Comment by GeertvanHorrik** [comment]
It's a single file change, and I need to fix the MAT resources so I'll do it. I am glad you did the investigation, made it extremely easy for me :)

**Pull request closed without merging**
