### PR TITLE
Created projects for EF7

### PR DESCRIPTION
**Pull request by SkyQuant**
Does _.IgnoreCatelProperties()_ extemsion work correctly with EF7? I found dependencies on EF6 only. Should I apply AutoMapper instead?

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
We haven't released an official version for EF 7 yet (because of dependency hell we decided to postpone it a bit). We might pick this up real soon though.

**Comment by SkyQuant** [comment]
What could you advice at the moment to resolve? I have some troubles downgrading to EF6 on VS 2015.

**Comment by GeertvanHorrik** [comment]
Uninstall EF and re-install it doesn't work for you?

**Comment by SkyQuant** [comment]
It asking .Commands library on Migration.

**Comment by SkyQuant** [comment]
Shoud I refresh entities manually with AutoMapper help before EF7 compatibility will be realised?

**Comment by GeertvanHorrik** [comment]
Yes, or copy/paste the extension method, it's reallyh just a simple thing:

https://github.com/Catel/Catel/blob/e8c26d4a8a7d09e2799f24f7f547650c4bf79433/src/Catel.Extensions.EntityFramework/Catel.Extensions.EntityFramework.Shared/Extensions/ConfigurationExtensions.cs

**Comment by SkyQuant** [comment]
Do I understand you right creating new class like on screenshot? https://yadi.sk/i/SOEN-c0limt3r

**Comment by GeertvanHorrik** [comment]
Correct, but in that case you will need to reference Catel.Core (since it requires ModelBase). But... if you really want EF support, you should just wait until we release a package since it will also support all the repositories / uow / etc.

**Comment by SkyQuant** [comment]
Ok, thank you. Looking forward for related news on RSS and Twitter soon.

**Comment by SkyQuant** [comment]
Suppose it's necessary somohow delete all methods additionaly to couple of properties
```
            modelBuilder.Entity<Person>()
                .Ignore(x => x.IsDirty)
                .Ignore(x => x.IsReadOnly)
                .Key(entity => entity.PersonId);
```
Result on screenshot
https://yadi.sk/i/jhiqfaXzin9Ee

**Comment by SkyQuant** [comment]
So, does new 4.2 version resolve EF7 problem or I need to wait special Data/EF extension update?

**Comment by GeertvanHorrik** [comment]
Correct, we didn't add EF 7 into 4.2 (it was already finished, we just wanted to wait if new bugs were introduced). I think EF7 will be part of 4.3. If you create an issue in the official issue tracker, it's easier for us to handle for releases.

**Comment by GeertvanHorrik** [comment]
btw see https://catelproject.atlassian.net/browse/CTL-678

**Pull request closed without merging**
