### PR TITLE
changed SynchronizeCollection to accept ICollection<T> instead of IList<T>

### PR DESCRIPTION
**Pull request by bigworld12**
changed from `IList<T>` to `ICollection<T>`

### Checklist

- [x] I have included examples or tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### CODE REVIEW

**Comment by bigworld12** [comment]
it's my first time committing here and i am not sure where the change log is, or whether i should add myself in the contributors even

**Comment by GeertvanHorrik** [comment]
Unfortunately this is a breaking change, so we need to think carefully about this.

**Comment by GeertvanHorrik** [comment]
A better (not sure whether it would compile though) would be:

```
public static IEnumerable<T> SynchronizeCollection<T>(this IList<T> existingSet, IEnumerable<T> newSet, bool updateExistingSet = true)
{
    return SynchronizeCollection((ICollection<T>)list), newSet, updateExistingSet);
}

public static IEnumerable<T> SynchronizeCollection<T>(this ICollection<T> existingSet, IEnumerable<T> newSet, bool updateExistingSet = true)
{
    ....
}
```

**Comment by bigworld12** [comment]
oh yeah we could add an overload for sure

**Comment by bigworld12** [comment]
but i don't think this is a breaking change, since `IList<T>` is implicitly castable to its parent `ICollection<T>`, on the contrary adding an overload that just casts the child to the parent is an overkill when the compiler does that already for you

**Comment by GeertvanHorrik** [comment]
But the runtime won’t be able to find the method. Sure, you will be able to recompile without issues, but other dependencies will still try to find the IList implementation, which they can’t, thus *boom*

________________________________

**Comment by bigworld12** [comment]
that's a valid point, but i think people will have to recompile it anyway since nuget doesn't distribute direct dlls

**Comment by GeertvanHorrik** [comment]
It does as implicit dependencies. For example, I update my app to new Catel, but use an “older” lib that was built against Catel 5.10, code from the lib will fail

________________________________

**Comment by bigworld12** [comment]
should be ok now

**Comment by GeertvanHorrik** [comment]
Perfect, thanks!

**Pull request merged**
