### PR TITLE
ChildAwareModelBase relays IsDirty changes to parent

### LINKED ISSUE #1166: Nesting with ChildAwareModelBase does not support more than one layer
When I run the unit test pasted below, the top level 'GrandParent' is not set to IsDirty=true when the child is changed. I would expect this to happen.

### Steps to reproduce

    public class GrandParent : ChildAwareModelBase
    {
      public void ResetIsDirty()
      {
        IsDirty = false;

      }
      public ObservableCollection<Parent> Children
      {
        get { return GetValue<ObservableCollection<Parent>>(ChildrenProperty); }
        set { SetValue(ChildrenProperty, value); }
      }

      public static readonly PropertyData ChildrenProperty = RegisterProperty(nameof(Children), typeof(ObservableCollection<Parent>), () => new ObservableCollection<Parent>());
    }

    public class Parent : ChildAwareModelBase
    {
      public void ResetIsDirty()
      {
        IsDirty = false;

      }
      public ObservableCollection<Child> Children
      {
        get { return GetValue<ObservableCollection<Child>>(ChildrenProperty); }
        set { SetValue(ChildrenProperty, value); }
      }

      public static readonly PropertyData ChildrenProperty = RegisterProperty(nameof(Children), typeof(ObservableCollection<Child>), () => new ObservableCollection<Child>());
    }

    public class Child : ChildAwareModelBase
    {
      public void ResetIsDirty()
      {
        IsDirty = false;

      }

      public string Name
      {
        get { return GetValue<string>(NameProperty); }
        set { SetValue(NameProperty, value); }
      }

      public static readonly PropertyData NameProperty = RegisterProperty(nameof(Name), typeof(string), null);

    }

    [TestFixture]
    class NestedChildAwareTest
    {
      [Test]
      public void TestNestedIsDirty()
      {
        var g = new GrandParent();
        var p = new Parent();
        var c = new Child();
        g.Children.Add(p);
        p.Children.Add(c);

        c.ResetIsDirty();
        p.ResetIsDirty();
        g.ResetIsDirty();

        Assert.IsFalse(c.IsDirty);
        Assert.IsFalse(p.IsDirty);
        Assert.IsFalse(g.IsDirty);

        c.Name = "Pietje";
        Assert.IsTrue(c.IsDirty);
        Assert.IsTrue(p.IsDirty);
        Assert.IsTrue(g.IsDirty); // THIS FAILS

      }
    }

Platform: Windows
.NET version: 4.6

### PR DESCRIPTION
**Pull request by mennodeij**
Fixes #1166 .

### Checklist

- [x] I have included examples or tests
- [ ] I have updated the change log **SORRY NOT FOUND**
- [x] I am listed in the CONTRIBUTORS file
- [ ] I have cleaned up the commit history (use rebase and squash)  **AFAIK, it is not advised to squash commits that were already pushed.**

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Not sure why we implemented that in the first time. Did all the other unit tests succeed? If so, then we can just merge this one.

**Comment by mennodeij** [comment]
There were three unit test that did not succeed:

* CorrectlySerializesConfiguration
* FormatMessage_SupportedContainers
* Returns_A_Released_Identifier_If_The_Instance_Is_Released_And_Reuse_Is_True

I see that one failure has to do with the line endings and all of them seem completely unrelated.

**Comment by GeertvanHorrik** [comment]
On the build server the PR succeeds, so all good :)

**Comment by GeertvanHorrik** [comment]
Thanks a lot for your contribution! FYI: the change log is in docs/history.txt

**Comment by mennodeij** [comment]
Ok, good to know thx

**Pull request merged**
