### PR TITLE
Updated WPF project's template to be compatible with VS2017

### PR DESCRIPTION
**Pull request by advapiIT**
Fixes # .

### Checklist

- [ ] I have removed Silverlight project templates
- [ ] I have removed WP8 project template
- [ ] I have updated project's template for WPF and Window Store App

### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Did you update your local develop branch before creating this PR? IT's important to keep your fork up-to-date.

1. git add remote upstream https://github.com/catel/catel
2. git pull upstream develop

You only have to do 1 once per repository.

**Comment by GeertvanHorrik** [comment]
Make sure to make a backup of your updated templates first so you can easily replace them afterwards. Can you explain what needed changed in the templates?

**Comment by advapiIT** [comment]
Excuse me for the late response but was really busy... I've just edited the Application.csproj and set the

`ToolsVersion="15.0"`

BTW I try to fix the pull...excuse me again...

**Comment by GeertvanHorrik** [comment]
@advapiIT did you pull the latest develop branch? It looks like we still have merge issues as you can see.

**Comment by advapiIT** [comment]
@GeertvanHorrik  I've some difficulties...I've commited to my gith the modification but not been able to do the PR

**Comment by GeertvanHorrik** [comment]
@advapiIT sorry for my late reply, I have been side-tracked. Did you try creating a new fork and re-apply the changes?

**Pull request closed without merging**
